services:

  grafana:
    image: grafana/grafana-oss
    restart: always
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_DATABASE_TYPE: "postgres"
      GF_DATABASE_HOST: "postgres:5432"
      GF_DATABASE_USER: "grafana"
      GF_DATABASE_PASSWORD: "grafana"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana:/etc/grafana/provisioning"
      - "var-lib-grafana:/var/lib/grafana"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgres/init-scripts:/docker-entrypoint-initdb.d"
      - var-lib-postgresql:/var/lib/postgresql/data

  rstudio:
    image: rocker/tidyverse
    restart: always
    environment: 
      - USER=analytics
      - PASSWORD=analytics
      - ROOT=TRUE
      - DISABLE_AUTH=TRUE
    ports:
      - "8787:8787"
    links:
      - postgres
    volumes:
      - "./rstudio:/home/rstudio"
      - var-lib-rstudio:/var/lib/rstudio

volumes:
  var-lib-grafana:
  var-lib-postgresql:
  var-lib-rstudio:
