version: '3.1'

services:

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - postgres
    env_file:
      - ./grafana/config.monitoring
    volumes:
      - ./grafana/dashboard:/etc/extra-config/grafana
    command: ./etc/extra-config/grafana/post.sh
    
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - 5432:5432                 # Postgres port
    volumes:
      - ./postgres/sql:/docker-entrypoint-initdb.d
