{
 "title": "RBC transfusion after Hb test",
 "time": { "from": "now-2y/y", "to": "now-1y/y" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "label": "Blood group",
    "query": "select blood_group from transfusion_hgb_2021;"
   },
   {
    "name": "query1",
    "label": "Hemoglobin",
    "query": "select level from transfusion_hgb_2021;"
   },
   {
    "name": "query2",
    "label": "Antibody",
    "query": "select antibody from transfusion_hgb_2021;"
   }
  ]
 },
 "panels": [
  {
   "title": "Patients",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  id\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Transfusions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  fin\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Volume transfused",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  volume\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Volume transfused",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  volume\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Time to transfusion",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Age (y)",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  age_year\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hemoglobin (g/dL)",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  hgb\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Time to transfusion (h)",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average time to transfusion",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  blood_group AS metric,\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average time to transfusion",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  level AS metric,\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average time to transfusion",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  antibody AS metric,\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average time to transfusion",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  donor_center AS metric,\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Time to transfusion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  blood_group AS metric,\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Time to transfusion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  level AS metric,\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Time to transfusion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  antibody AS metric,\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Time to transfusion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  donor_center AS metric,\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Transfusion locations",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  location AS metric,\n  hours\nFROM transfusion_hgb_2021\nWHERE\n  $__timeFilter(time) AND\n  blood_group IN ($query0) AND\n  level IN ($query1) AND\n  antibody IN ($query2)\nORDER BY 1,2"
    }
   ]
  }
 ]
}